### ISSUE TITLE
[modify] 유틸함수로 교체, 코드 정리, 썸네일 구현

### ISSUE THREAD

**Issue by hyundonmoon** [wanted-pre-onboading-10/rakuten-symphony-transfer#10]
# TASK CARD

Task Description : 현재 date-fns, filesize 패키지 사용하고 있는 부분을 팀원들이 만든 유틸함수로 교체하고, 썸네일 안 나오는 문제 해결하고, 지저분한 코드 정리하기

Date : 2022-02-23

## to-do

- [x] 링크 생성 날짜, 만료 되었는지 테스트하는 부분 유틸함수로 교체
- [x] 파일 사이즈 변환하는 부분 유틸함수로 교체
- [x] 현재 svg형태의 썸네일들이 접근 불가한 상태라 안 뜨는데 이거 해결하기
- [x] 컴포넌트로 분리할 수 있는 부분은 빼내기
