### ISSUE TITLE
[feat] 링크 상세 화면 구현

### ISSUE THREAD

**Issue by hyundonmoon** [wanted-pre-onboading-10/rakuten-symphony-transfer#2]
# TASK CARD

Task Description : 링크 상세 화면 구현

Date : [작업일]

## to-do

- [x] 링크 정보를 표시
- [x] 받기 버튼을 누르면 다운로드 되었습니다.를 내용으로 가지는 브라우저 기본 Alert을 표시
- [x] 링크의 유효기간이 만료 되지 않았을 경우에만 파일 목록을 표시
