### ISSUE TITLE
[feat] list 표시

### ISSUE THREAD

**Issue by tae100k** [wanted-pre-onboading-10/rakuten-symphony-transfer#5]
# TASK CARD

Task Description : axios로 받은 데이터들을 바인딩 및 상세 처리

Date : 2022.02.04

## to-do

- [x] axios를 사용해 api 받아와서, 하드코딩된 데이터들 바인딩
- [x] 아이템 클릭시 상세페이지로 이동
- [x] 유효기간에 따라 제목 아래 url에 선택적으로 (도메인 주소+상세페이지 경로) or 만료됨 표시
- [x] 상세페이지 경로 url 클릭 시 alert창
- [x]  상세페이지 경로 url 클릭 시 alert창 유효기간 만료시 아무 동작X
- [x] 받은 사람이 존재할 경우, Avatar 컴포넌트 사용
